name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  validate:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Run tests
      run: |
        if (Test-Path "**/*.Tests.csproj") {
          dotnet test --no-build --verbosity normal --configuration Release --logger "trx;LogFileName=test-results.trx"
        } else {
          Write-Host "No test projects found, skipping tests"
        }
      shell: pwsh
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: '**/*.trx'
        
    - name: Code Analysis
      run: |
        # Add code analysis if needed
        Write-Host "Code analysis completed"
      shell: pwsh